name: "Publish Doxygen Docs"
description: "Generate and push the Doxygen docs to the S3 bucket."
inputs:
  version:
    description: "The version string to paste into the docs."
    required: true
  destination:
    description: "The destination directory on the S3 bucket."
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: Build docs
      uses: mattnotmitt/doxygen-action@1.9.4
      env:
        DOXYGEN_PROJECT_NUMBER: ${{ inputs.version }}
    - name: Upload docs
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.DOCS_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: docs/html
        DEST_DIR: docs/realm-sdks/cpp/${{ inputs.destination }}
