name: "Publish Doxygen Docs"
description: "Generate and push the Doxygen docs to the S3 bucket."
inputs:
  version:
    description: "The version string to paste into the docs."
    required: true
  destination:
    description: "The destination directory on the S3 bucket."
    required: true
  AWS_S3_BUCKET:
    description: "The AWS S3 bucket name."
    required: true
  AWS_ACCESS_KEY_ID:
    description: "The AWS public key."
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "The AWS private key."
    required: true
runs:
  using: "composite"
  steps:
    - name: Build docs
      uses: mattnotmitt/doxygen-action@1.9.4
      env:
        DOXYGEN_PROJECT_NUMBER: ${{ inputs.version }}
    - name: Fix doxygen titles for SEO
      shell: bash
      run: bash /docs/fix-doxygen-titles.sh
    - name: Upload docs
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: docs/html
        DEST_DIR: docs/realm-sdks/cpp/${{ inputs.destination }}
