name: Test Conan integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
        linkage_is_dynamic: ["True", "False"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Conan profile detect
        working-directory: .
        run: |
          conan profile detect

      - name: Update Conan profile
        if: matrix.os == 'windows-latest'
        run: |
          $profilePath = "$env:USERPROFILE\.conan2\profiles\default"
          $content = Get-Content -Path $profilePath
          $content = $content -replace 'compiler.cppstd=14', 'compiler.cppstd=17'
          $content | Set-Content -Path $profilePath

      - name: Conan create
        working-directory: .
        run: |
          conan create . -tf="tests" -s build_type=${{ matrix.build_type }} -o use_libuv=True -o shared=${{ matrix.linkage_is_dynamic }} --build=missing

      - name: Open a tmate debug session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 15