name: Publish Doxygen Docs Latest

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish-doxygen
        with:
          version: Alpha version ${{ github.ref_name }}@${{ github.sha }}
          destination: latest
