name: SwiftPM Build

env:
  REALM_CI: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-12
    name: ${{ matrix.platform }} ${{ matrix.configuration }}, Xcode ${{ matrix.xcode }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macOS
          - macOS,variant=Mac Catalyst
          - iOS
          - iOS Simulator
          - tvOS
          - tvOS Simulator
        xcode:
          - '13.2.1'
          - '14.0'
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - uses: ammaraskar/gcc-problem-matcher@master

      - name: Build
        run: |
          # Xcode 13 can't build executable targets for non-macOS platforms
          scheme=realm-cpp-sdk
          if [[ "${{ matrix.platform }}" == macOS* ]] || [[ "${{ matrix.xcode }}" != 13.* ]]; then
            scheme=realm-cpp-sdkTests
          fi
          xcodebuild -scheme $scheme -destination "generic/platform=${{ matrix.platform }}" -configuration ${{ matrix.configuration }} -derivedDataPath .build/derivedData
      
      - name: Open a tmate debug session
        if: ${{ failure() && runner.debug }}
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 15
